apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace: st-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: dikshaop/apache:latest
          ports:
            - containerPort: 80
            - containerPort: 443

         
